### ISSUE TITLE
Fn::Length returns 1 even if CommaDelimitedList value is blank in Parameterers

### ISSUE THREAD

**Issue by shiosalt** [aws-cloudformation/cfn-language-discussion#102]
### **Tell us about the bug**
Fn::Length returns 1 even if CommaDelimitedList value is blank in Parameterers.
Please see the template in "Test cases".

Here is a processed template with "IPList"  "10.10.20.0/24".
You can see "IPList" becomes ["10.10.20.0/24"], so { "Fn::Length": { "Ref": "IPList" } returns 1.
Great.
```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Parameters": {
    "IPList": {
      "Type": "CommaDelimitedList"
    }
  },
  "Resources": {
    "WafIpSet": {
      "Type": "AWS::WAFv2::IPSet",
      "Condition": "IPExists",
      "Properties": {
        "Addresses": [
          "10.10.20.0/24"
        ],
        "Description": "sample IP list",
        "IPAddressVersion": "IPV4",
        "Scope": "REGIONAL"
      }
    }
  },
  "Conditions": {
    "IPExists": {
      "Fn::Not": [
        {
          "Fn::Equals": [
            1,
            0
          ]
        }
      ]
    }
  }
}
```

Here is an another processed template with "IPList" blank.
You can see "IPList" becomes [""], so { "Fn::Length": { "Ref": "IPList" } returns 1.
Not Good. That's correct, but not the desired result.
I want 0 in this situation.
```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Parameters": {
    "IPList": {
      "Type": "CommaDelimitedList"
    }
  },
  "Resources": {
    "WafIpSet": {
      "Type": "AWS::WAFv2::IPSet",
      "Condition": "IPExists",
      "Properties": {
        "Addresses": [
          ""
        ],
        "Description": "sample IP list",
        "IPAddressVersion": "IPV4",
        "Scope": "REGIONAL"
      }
    }
  },
  "Conditions": {
    "IPExists": {
      "Fn::Not": [
        {
          "Fn::Equals": [
            1,
            0
          ]
        }
      ]
    }
  }
}
```
### **Expected behavior**
Fn::Length returns 0 when CommaDelimitedList value is blank in Parameterers.

### **Test cases**
Please include a minimal CloudFormation template here that reproduces the issue
```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Transform": "AWS::LanguageExtensions",
  "Parameters": {
    "IPList": {
      "Type": "CommaDelimitedList"
    }
  },
  "Conditions": {
    "IPExists": {
      "Fn::Not": [
        {
          "Fn::Equals": [{ "Fn::Length": { "Ref": "IPList" } }, 0]
        }
      ]
    }
  },
  "Resources": {
    "WafIpSet": {
      "Type": "AWS::WAFv2::IPSet",
      "Condition": "IPExists",
      "Properties": {
        "Addresses": {
          "Ref": "IPList"
        },
        "Description": "sample IP list",
        "IPAddressVersion": "IPV4",
        "Scope": "REGIONAL"
      }
    }
  }
}
```
### **Additional context**
Thanks for providing this language extension. Especially I love intrinsic support for DeletionPolicy.
I'm sorry if my writing is rude.English is not my first language.

**Comment by josb** [comment]
> Fn::Length returns 0 for a CommaDelimitedList with value "" because {"Ref": "CommaDelimitedParameter"} returns [""] and not [].

@arthurboghossian don't you mean 1 instead of 0?

**Comment by arthurboghossian** [comment]
Good point @josb! I've updated the comment accordingly
