### ISSUE TITLE
Tracking Issue: Allow Intrinsic Functions and Pseudo-Parameter References in `DeletionPolicy` and  `UpdateReplacePolicy` RFC

### ISSUE THREAD

**Issue by mingujo** [aws-cloudformation/cfn-language-discussion#11]
Original Issue: [Support Functions as DeletionPolicy/UpdateReplacePolicy Values aws-cloudformation/cfn-language-discussion#58](https://github.com/aws-cloudformation/cfn-language-discussion/issues/58)

---
Name: "Allow Intrinsic Functions and Pseudo-Parameter References in `DeletionPolicy` and  `UpdateReplacePolicy` RFC Tracking Issue"

About: "Tracking issue for Allow Intrinsic Functions and Pseudo-Parameter References in `DeletionPolicy` and  `UpdateReplacePolicy` RFC"

Title: Allow Intrinsic Functions and Pseudo-Parameter References in `DeletionPolicy` and  `UpdateReplacePolicy` RFC

Labels: management/tracking, status/proposed

---

## Description

Short description of the proposed feature.

## Checklist

- [x] Tracking issue created (label: `status/proposed`)
- [x] RFC pull request submitted 
- [x] Reviewers assigned (label: `status/review`)
- [x] Reviewers signed-off (label `approved` applied to pull request)
- [x] Final comments period (label: `status/final-comments-period`)
- [x] Approved and merged (label: `status/approved`)
- [x] Implementation started (label: `status/implementing`)
- [x] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by atreyd** [comment]
Is there any updates or ETA for release this feature in cloudformation. ? We are waiting on this feature to be available to manage our resources effectively for different types of environments.

**Comment by jlhood** [comment]
@atreyd Thanks for your interest! We're not able to provide specific ETAs publicly, but rest assured we're working on it. Stay tuned!

**Comment by lejiati** [comment]
Close this issue as this feature is now [available](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/function-refs-in-policy-attributes.html)
