### ISSUE TITLE
Move Feature Requests from CFN resource coverage repo

### ISSUE THREAD

**Issue by richardhboyd** [aws-cloudformation/cfn-language-discussion#30]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### **Tell us about your request**
Someone should move all of the issues in the CFN resource coverage repo that are CFN language specific from that repo to this one.

### **Tell us about the problem you are trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? 
What is the impact of not having this problem solved? The more details you can provide, the better we will be able to understand and solve the problem.

Those issues belong in this repo (some were probably prematurely closed since they weren’t resource coverage issues)

### **Are you currently working around this issue?**
How are you currently solving this problem?

DMing jlhood on Slack

### **What is the expect behavior with this new feature**
Please include some code examples showing how this feature can be used.

N/A

### **Additional context**
Anything else we should know?

### **Attachments**
If you think you might have additional information that you wouldd like to include via an attachment, 
please do - we will take a look. (Remember to remove any personally-identifiable information.)
N/A

**Comment by jlhood** [comment]
@richardhboyd Yep, we're working on it! 😊

**Comment by jlhood** [comment]
Done
