### ISSUE TITLE
Fn::Serialize Intrinsic Function

### ISSUE THREAD

**Issue by the-avid-engineer** [aws-cloudformation/cfn-language-discussion#42]
### Name of the resource

Other

### Resource name

All

### Description

There seems to be several resources which require JSON policy documents, but CloudFormation needs you to give it a `string` instead of a `Json`. It would be super nifty if there was an intrinsic function that serializes JSON.

Consider the ECR Repository's LifecyclePolicyText. It is a JSON object, but the CloudFormation engine needs it to be serialized as a string; it won't accept a JSON object. The `Fn::Serialize` intrinsic function would allow you to represent the policy as a JSON object in your template file!

```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Resources": {
    "Registry": {
      "Type": "AWS::ECR::Repository",
      "Properties": {
        "LifecyclePolicy": {
          "LifecyclePolicyText": {
            "Fn::Serialize": {
              "rules": [
                {
                  "rulePriority": 1,
                  "description":"limit to most-recent 100 images",
                  "selection": {
                    "tagStatus":"any",
                    "countType":"imageCountMoreThan",
                    "countNumber":100
                  },
                  "action": {
                    "type":"expire"
                  }
                }
              ]
            }
          }
        },
        "RepositoryName": {
          "Ref": "AWS::StackName"
        }
      }
    }
  }
}
```

Is automatically translated to the following:

```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Resources": {
    "Registry": {
      "Type": "AWS::ECR::Repository",
      "Properties": {
        "LifecyclePolicy": {
          "LifecyclePolicyText": "{\"rules\":[{\"rulePriority\":1,\"description\":\"limit to most-recent 100 images\",\"selection\":{\"tagStatus\":\"any\",\"countType\":\"imageCountMoreThan\",\"countNumber\":100},\"action\":{\"type\":\"expire\"}}]}"
        },
        "RepositoryName": {
          "Ref": "AWS::StackName"
        }
      }
    }
  }
}
```

### Other Details

No more having to deal with escaped quotation marks. Just work with pure JSON.

**Comment by lejiati** [comment]
Hi @the-avid-engineer we have a new language RFC https://github.com/aws-cloudformation/cfn-language-discussion/pull/76 created which should address this issue. Feel free to take a look and leave comments

I'll close this issue as it's duplicate but feel free to reopen if you have any questions.
