### ISSUE TITLE
Fn::JsonString

### ISSUE THREAD

**Issue by Sviat** [aws-cloudformation/cfn-language-discussion#53]
## 1. Title
Fn::JsonString

## 2. Scope of request 
JSON CloudFormation Templates.

Whenever a resource has property that requires content as JSON String, we all either write this Fn::Join's with "\n" and other workarounds, or convert JSON to String by external tool.

This lowers readability of code (Infrastructure is a Code!) to zero, and highers maintenance costs.
Example: 
## 3. Expected behavior
Instead of trying to construct string out of JSON key-values and Fn::Ref's / Fn::GetAtt's, should be possible to assign property JSON object and hope CloudFormation will handle the rest.

Example:

`    "Resources": {
        "Dashboard": {
            "Type" : "AWS::CloudWatch::Dashboard",
            "Properties" : {
                "DashboardName" : "Lorem Ipsum 42",
                "DashboardBody" : { "Fn::JsonString": { 
  "Key1": "Value",
  "Key2": { "Fn::Ref": "SomeId" },
  "Key3": { ... }
}
}` 

## 4. Suggest specific test cases
See 3.

## 6. Category
11. Other (IoT, Migration, Budgets...) -  Intrinsic Functions

**Comment by MalikAtalla-AWS** [comment]
Hey all, we have created an RFC to address this problem. We invite you to have your say there as well:
https://github.com/aws-cloudformation/cfn-language-discussion/issues/14

**Comment by lejiati** [comment]
Hi all, really appreciate all the feedback and feature proposal. I'm excited that share that now you can now convert JSON objects into JSON string with [`Fn::ToJsonString`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-ToJsonString.html) now. Please try it out and feel free to leave your comments here!

**Comment by MalikAtalla-AWS** [comment]
Since `Fn:ToJsonString` is now available, we can close this issue

**Comment by tyliggity** [comment]
Hi.  So, `Fn:ToJsonString` did not solve this for me.  I am getting this same error:
```Properties validation failed for resource ComputeEnvironment1 with message: #/ComputeResources/Tags: expected type: JSONObject, found: String```

Here is the template snippet I'm using.
```yaml
        Tags:
          Fn::ToJsonString:
            Name: !Sub ${EnvironmentName}-data-etl-ce-1"
```
