### ISSUE TITLE
Fn::Size intrinsic template function

### ISSUE THREAD

**Issue by josb** [aws-cloudformation/cfn-language-discussion#61]
## Scope of request
AWS CloudFormation templates.
## Expected behavior
`Fn::Size` should return the number of elements in a list (the result of `Fn::Split`, or a `CommaDelimitedList` parameter).
## Test case recommendation
If you combine this with the `Fn::Split` function it will allow you to see how many items were entered when someone has a `CommaDelimitedList` parameter, which is helpful when it comes to Conditionals:
`{ "Fn::Size" : { "Fn::Split" : [ "delimiter", "source string" ] } }`
## Links to existing API doc
https://www.kencochrane.net/2017/03/25/my-cloudformation-wishlist/
## Category
11. Other (IoT, Migration, Budgets...)

**Comment by muneebar** [comment]
@josb Thanks for bringing this to our attention. This feature request is a duplicate of [#37](https://github.com/aws-cloudformation/cfn-language-discussion/issues/37). I will close this issue and invite you to follow [#37](https://github.com/aws-cloudformation/cfn-language-discussion/issues/37) for further updates.

**Comment by MalikAtalla-AWS** [comment]
Hi all, we have opened an RFC ([here](https://github.com/aws-cloudformation/cfn-language-discussion/pull/72)) to address this use case. Any feedback is welcome.

**Comment by josb** [comment]
Thanks to all helping to submit this RFC!

**Comment by josb** [comment]
Hello @lejiati, we'll try the new function, thanks for making this happen!

**Comment by josb** [comment]
`Fn::Length` is now [available](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-length.html), hence closing this.
