### ISSUE TITLE
RFC for Fn::Length Support

### ISSUE THREAD

**Issue by juegong2** [aws-cloudformation/cfn-language-discussion#70]
## Description

We will support an intrinsic function called `Fn::Length` that will return the number of elements in a given list. 

## Checklist

- [x] Tracking issue created (label: `status/proposed`)
- [x] RFC pull request submitted 
- [x] Reviewers assigned (label: `status/review`)
- [x] Reviewers signed-off (label `approved` applied to pull request)
- [x] Final comments period (label: `status/final-comments-period`)
- [x] Approved and merged (label: `status/approved`)
- [x] Implementation started (label: `status/implementing`)
- [x] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by josb** [comment]
Would it be out of scope for this intrinsic function to also return the number of characters | bytes | codepoints when passed a single string instead of a list?

**Comment by josb** [comment]
Some resource identifiers are limited in length; this would allow logic to be written to mitigate situations where resources would otherwise produce errors (e. g. the logic could construct shorter names to work around length limitation issues).

**Comment by benkehoe** [comment]
Would something that does that operation more directly be a better solution?

**Comment by josb** [comment]
I'm not sure what a general-purpose solution to that problem  would look like, sorry.

That said, it would appear that a way to do numeric size comparisons in `!If` (beyond `!Equals`) would also be needed to address the use case where I think `!Length` would be useful, so perhaps this is a non-starter for now anyway.

**Comment by benbridts** [comment]
> I'm not sure what a general-purpose solution to that problem would look like, sorry.

It could be something similar to [GenerateResourceIdentifier](https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/d86fdd3775914caf56e906911945289ec38055da/src/main/java/software/amazon/cloudformation/resource/IdentifierUtils.java#L65) (which can be used by resource providers to generate logical ids),

Or there could be a cut/trim function

```
# this one would always add a random string
Fn::GenerateIdentifier [ $name, $maxlength ]

# this one would drop characters at the end
Fn::Cut[$string, $maxlength]
```

**Comment by josb** [comment]
Good suggestions, @benbridts. This function, as I originally intended it to be used, would be more useful if (numeric) comparison operators were available besides `!Equals`. Sigh.

**Comment by MalikAtalla-AWS** [comment]
Hey @benbridts and @josb. We really appreciate all your feedback. You mention some interesting ideas about better support for numeric comparisons or new intrinsic functions like Fn::GenerateIdentifier/Fn::Cut. If you want to create new issues in this repo briefly describing your proposals then we would have a good way to gauge demand from the community (through likes and comments).

**Comment by josb** [comment]
@MalikAtalla-AWS I filed https://github.com/aws-cloudformation/cfn-language-discussion/issues/80 to add comparison functions which can be used in combination with Fn::Length and possibly other constructs.

**Comment by bjorg** [comment]
I know I'm too late to the party, but disguising functionality that is introduced by transforms as native CloudFormation intrinsic is confusing. This shouldn't have had just the "Fn::" prefix. It should be immediately clear to a reader that it is not part of CloudFormation natively. For example, something like "Fn::Tx::Length" would make it clearer that this is not your usual intrinsic function.

I was elated when I first read the announcement about `Fn::Length`. _"Finally, there is movement on extending CloudFormation!"_ I thought. But then, much to my dismay, I discovered this was done via a transform, which brings all kinds of quirks along with it, such as not being able to operate on computed values and depending on the order in which transforms are applied.

Mayb a better alternative would be to invoke it explicitly using `Fn::Transform`? That would allow for it to operate on generated values, but I'm not sure what it would look like--or if it's even possible.

**Comment by josb** [comment]
I, too, was surprised that to use the new functions one needs a transform. That certainly wasn't my intention, as transforms have their own issues, as @bjorg alludes to. 

I would say that if a transform is required, to be consistent the old, existing functions should be moved into that transform after a suitable migration period. But no transform would be preferred as there should be no name collisions at this point.

**Comment by myahl-uncomn** [comment]
My team is not allowed to use transforms due to the aforementioned quirks/issues and lack of visibility of the transformed template during deployment. Moving the existing intrinsic functions to transforms would be a nightmare for us.

**Comment by josb** [comment]
If we leave things as-is, it introduces an inconsistency regarding these new functions. To be clear, I'm not a fan of moving all functions into the transform, in fact I want the opposite to happen.

**Comment by jlhood** [comment]
@bjorg Thanks so much for your feedback. The language extension approach we took allows us to iterate on new functions faster than if they were part of the native template processor. Our goal in creating this public repo, the RFC approach, and the transform are to collect input from the community and quickly deliver on new language improvements. We acknowledge there will be some limitations as well as language enhancements that cannot be performed with `AWS::LanguageExtensions` but our velocity for publishing new functions goes up significantly with this approach.

@josb We do not have plans to move intrinsic functions out of the native template processor into the `AWS::LanguageExtensions` transform.

@myahl-uncomn Thank you for your feedback. Re: Lack of visibility of the transformed template during deployments, you can access and inspect the transformed template prior to deploying it by creating a change set and then, prior to executing it, either viewing the change set in the AWS CloudFormation console, selecting the Template tab, and toggling "View processed template" or by calling the [GetTemplate API](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_GetTemplate.html), passing the change set name and setting the `TemplateStage` parameter to `Processed`.

**Comment by josb** [comment]
@jlhood will the new functions be migrated to the native template processor after a suitable soaking period? The long-term split between the native and transform-based template processor seems unfortunate, in particular because as you mentioned there are limitations associated with the transform-based mechanism.

**Comment by josb** [comment]
As an aside, my pet peeve with the "View processed template" feature of the CloudFormation console is that there's no choice between JSON and YAML.

**Comment by jlhood** [comment]
@josb I can't comment on future roadmap/features, but I agree that integrating them into the native template processor would be more ideal in the long-term.

Appreciate your feedback on the "View processed template" feature. I've passed this along to the team.

**Comment by josb** [comment]
Excellent, thanks @jlhood! Of course I am grateful regardless for your work on new functions, it's great to see activity in this space. 👍 to you and the team!

**Comment by myahl-uncomn** [comment]
> Re: Lack of visibility of the transformed template during deployments, you can access and inspect the transformed template prior to deploying it by creating a change set and then, prior to executing it, either viewing the change set in the AWS CloudFormation console, selecting the Template tab, and toggling "View processed template" or by calling the [GetTemplate API](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_GetTemplate.html), passing the change set name and setting the TemplateStage parameter to Processed.

@jlhood Thanks for this explanation! I'll be sure to point it out to my team. I appreciate all the work you guys are doing here.

**Comment by lejiati** [comment]
Thank you all for the feedback! I'm closing this issue it's `Fn::Length` is [available](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-length.html) now.
