### ISSUE TITLE
Completed features should have a link to documentation for them

### ISSUE THREAD

**Issue by benkehoe** [aws-cloudformation/cfn-language-discussion#94]
I think in [the table](https://github.com/aws-cloudformation/cfn-language-discussion#what-is-it) in the README, there should be a link to the released documentation for features that have shipped.

It could also be more clear the involvement of the `AWS::LanguageExtensions` transform, that these features will ship as part of it, etc.

**Comment by jlhood** [comment]
Appreciate the suggestion, Ben!

**Comment by jlhood** [comment]
Done!
